using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Euler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Euler002 : IEulerProblem
    {
        public string Solve()
        {
            int fib = 0;
            int n = 0;
            int m = 1;
            int result = 0;
            while((n + m) < 4000000)
            {
                fib = n + m;
                n = m;
                m = fib;
                if(IsEven(fib))
                {
                    result += fib;
                    Console.WriteLine(fib);
                }
            }
            return string.Format("Result = {0}", result);
        }

        private static bool IsEven(int value)
        {
            return ((value & 1) == 0);
        }

    }
}
